/*
Student Name:Swaumya Pokharel
Subject     :Programming fund
Roll        :
Program     :Write a program to print the square root of any two numbers
lab no.     :
Date        :18 September,2016
*/
#include<stdio.h>
#include<conio.h>
	void main()
	{
	float a,square;
	clrscr();
	printf("Enter any number:\n");
	scanf("%f",&a);
	square=a*a;
	printf("The square of the given number is=%f",square);
	getch();
	}